import type { Prisma } from "@prisma/client";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Search } from "lucide-react";
import { EvaluationBatchControls } from "@/components/evaluation-batch-controls";
import { EvaluationResultsTable } from "@/components/evaluation-results-table";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { evaluationMetrics, evaluationResultStatuses, type EvaluationResultStatus } from "@/lib/evaluation";
import { EVALUATION_RESULT_PAGE_SIZE, evaluationResultHref, evaluationResultSorts, parseEvaluationResultSearch } from "@/lib/evaluation-search";
import { prisma } from "@/lib/prisma";

const selectClass = "h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-700 shadow-sm outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100";

export default async function EvaluationBatchPage({ params, searchParams }: { params: Promise<{ batchId: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { batchId } = await params; const search = parseEvaluationResultSearch(await searchParams);
  const batch = await prisma.evaluationBatch.findUnique({ where: { id: batchId }, include: { task: { select: { id: true, title: true, project: { select: { id: true, name: true } } } }, results: { select: { status: true, reward: true, executionTimeMs: true, modelName: true, modelVersion: true, temperature: true, seed: true } } } });
  if (!batch) notFound();
  const where: Prisma.EvaluationResultWhereInput = { evaluationBatchId: batch.id, ...(search.status ? { status: search.status } : {}), ...(search.q ? { OR: [{ candidateResponse: { contains: search.q } }, { externalId: { contains: search.q } }] } : {}) };
  const total = await prisma.evaluationResult.count({ where }); const totalPages = Math.max(1, Math.ceil(total / EVALUATION_RESULT_PAGE_SIZE)); const page = Math.min(search.page, totalPages);
  const orderBy: Prisma.EvaluationResultOrderByWithRelationInput[] = search.sort === "reward" ? [{ reward: "desc" }, { sequenceNumber: "asc" }] : search.sort === "execution" ? [{ executionTimeMs: "desc" }, { sequenceNumber: "asc" }] : search.sort === "evaluated" ? [{ evaluatedAt: "desc" }, { sequenceNumber: "asc" }] : [{ sequenceNumber: "asc" }];
  const rows = await prisma.evaluationResult.findMany({ where, orderBy, skip: (page - 1) * EVALUATION_RESULT_PAGE_SIZE, take: EVALUATION_RESULT_PAGE_SIZE });
  const metrics = evaluationMetrics(batch.results, batch.importInvalidCount); const groups = grouped(batch.results);
  return <div className="space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><Link className="text-sm font-medium text-slate-500 hover:text-indigo-600" href="/dashboard/evaluations">← Evaluations</Link><div className="mt-4 flex items-center gap-2"><Badge>{batch.status}</Badge><span className="text-xs text-slate-500">{label(batch.sourceType)}</span></div><h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-950">{batch.name}</h1><p className="mt-2 text-slate-500">{batch.description || "No description"}</p></div><EvaluationBatchControls batchId={batch.id} status={batch.status} counts={{ total: batch.results.length, failed: batch.failedCount, errors: batch.errorCount }} exportStatus={search.status || undefined} /></div>
    {(batch.status === "RUNNING" || batch.status === "QUEUED") && <Card><CardContent className="py-5"><div className="mb-2 flex justify-between text-sm"><span>Evaluation progress</span><strong>{batch.progress}%</strong></div><progress className="h-2 w-full accent-indigo-600" max="100" value={batch.progress}>{batch.progress}%</progress></CardContent></Card>}{batch.status === "FAILED" && <p className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{batch.errorMessage || "Evaluation failed and can be retried."}</p>}{batch.status === "CANCELLED" && <p className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Evaluation cancelled. Completed results are preserved and pending work can be retried.</p>}
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Total" value={batch.requestedCount} /><Metric label="Processed" value={batch.processedCount} /><Metric label="Passed" value={batch.passedCount} /><Metric label="Failed" value={batch.failedCount} /><Metric label="Pass rate" value={percent(metrics.passRate)} /><Metric label="Invalid" value={batch.invalidCount} /><Metric label="Errors" value={batch.errorCount} /><Metric label="Average reward" value={metrics.averageReward.toFixed(3)} /><Metric label="Average time" value={`${metrics.averageVerificationTime.toFixed(3)} ms`} /><Metric label="Median time" value={`${metrics.medianVerificationTime.toFixed(3)} ms`} /><Metric label="Min / max time" value={`${metrics.minimumVerificationTime.toFixed(3)} / ${metrics.maximumVerificationTime.toFixed(3)} ms`} /><Metric label="Duplicates" value={batch.duplicateCount} /></div>
    <div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><h2 className="font-semibold">Task and verifier snapshot</h2></CardHeader><CardContent className="space-y-3 text-sm"><p><Link className="font-semibold text-indigo-700" href={`/dashboard/projects/${batch.task.project.id}/tasks/${batch.task.id}`}>{batch.taskTitleSnapshot}</Link> · {batch.task.project.name}</p><p className="whitespace-pre-wrap text-slate-600">{batch.taskPromptSnapshot}</p><p className="text-xs text-slate-500">Task snapshot from {batch.taskUpdatedAtSnapshot.toLocaleString()}</p><pre className="overflow-x-auto rounded-lg bg-slate-950 p-4 text-xs text-slate-100">{JSON.stringify({ type: batch.verifierTypeSnapshot, config: batch.verifierConfigSnapshot }, null, 2)}</pre></CardContent></Card><Card><CardHeader><h2 className="font-semibold">Run metadata</h2></CardHeader><CardContent><dl className="grid grid-cols-2 gap-3 text-sm"><Meta label="Model" value={batch.modelName} /><Meta label="Version" value={batch.modelVersion} /><Meta label="Temperature" value={batch.temperature} /><Meta label="Top-p" value={batch.topP} /><Meta label="Seed" value={batch.seed} /><Meta label="Created by" value={batch.createdBy ? label(batch.createdBy) : null} /><Meta label="Created" value={batch.createdAt.toLocaleString()} /><Meta label="Duration" value={duration(batch.startedAt, batch.completedAt)} /></dl></CardContent></Card></div>
    <Card><CardHeader><h2 className="font-semibold">Results by model metadata</h2></CardHeader><CardContent>{groups.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="pb-2">Model</th><th>Version</th><th>Temperature</th><th>Seed</th><th>Results</th><th>Pass rate</th></tr></thead><tbody>{groups.map((group) => <tr className="border-b border-slate-100" key={group.key}><td className="py-3">{group.model}</td><td>{group.version}</td><td>{group.temperature}</td><td>{group.seed}</td><td>{group.total}</td><td><div className="flex items-center gap-2"><span>{percent(group.passRate)}</span><span className="h-2 w-20 overflow-hidden rounded bg-slate-100"><span className="block h-full bg-emerald-500" style={{ width: percent(group.passRate) }} /></span></div></td></tr>)}</tbody></table></div> : <p className="text-sm text-slate-500">No evaluated metadata groups yet.</p>}</CardContent></Card>
    <Card className="overflow-hidden"><CardHeader><h2 className="font-semibold">Individual results</h2><form className="mt-4 grid gap-3 md:grid-cols-4" method="get"><label className="relative md:col-span-2"><Search className="pointer-events-none absolute left-3 top-3 size-4 text-slate-400" /><Input className="pl-9" defaultValue={search.q} name="q" placeholder="Search response or external ID" /></label><select className={selectClass} defaultValue={search.status} name="resultStatus"><option value="">All statuses</option>{evaluationResultStatuses.map((status) => <option key={status} value={status}>{label(status)}</option>)}</select><select className={selectClass} defaultValue={search.sort} name="resultSort">{evaluationResultSorts.map((sort) => <option key={sort} value={sort}>{label(sort)}</option>)}</select><div className="flex gap-2 md:col-span-4"><button className={buttonVariants({ size: "sm" })} type="submit">Apply</button><Link className={buttonVariants({ variant: "secondary", size: "sm" })} href={`/dashboard/evaluations/${batch.id}`}>Reset</Link></div></form></CardHeader><EvaluationResultsTable batchId={batch.id} rows={rows.map((row) => ({ ...row, evaluatedAt: row.evaluatedAt?.toISOString() ?? null }))} previousHref={page > 1 ? evaluationResultHref(batch.id, search, page - 1) : undefined} nextHref={page < totalPages ? evaluationResultHref(batch.id, search, page + 1) : undefined} /></Card>
  </div>;
}

function Metric({ label: text, value }: { label: string; value: React.ReactNode }) { return <Card><CardContent className="py-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{text}</p><p className="mt-2 text-2xl font-bold text-slate-950">{value}</p></CardContent></Card>; }
function Meta({ label: text, value }: { label: string; value: unknown }) { return <div><dt className="text-slate-500">{text}</dt><dd className="mt-1 font-medium text-slate-900">{value === null || value === undefined || value === "" ? "—" : String(value)}</dd></div>; }
function label(value: string) { return value.toLowerCase().replaceAll("_", " ").replace(/^./, (character) => character.toUpperCase()); }
function percent(value: number) { return `${(value * 100).toFixed(1)}%`; }
function duration(start: Date | null, end: Date | null) { return start && end ? `${Math.max(0, end.getTime() - start.getTime())} ms` : "—"; }
function grouped(results: { status: EvaluationResultStatus; reward: number | null; executionTimeMs: number | null; modelName: string | null; modelVersion: string | null; temperature: number | null; seed: number | null }[]) { const values = new Map<string, typeof results>(); for (const result of results) { const key = JSON.stringify([result.modelName, result.modelVersion, result.temperature, result.seed]); values.set(key, [...(values.get(key) ?? []), result]); } return [...values].map(([key, rows]) => { const [model, version, temperature, seed] = JSON.parse(key) as [string | null, string | null, number | null, number | null]; const metrics = evaluationMetrics(rows); return { key, model: model || "Unspecified", version: version || "—", temperature: temperature ?? "—", seed: seed ?? "—", total: rows.length, passRate: metrics.passRate }; }); }
