ALTER TABLE "TaskImport" ADD COLUMN "strategy" TEXT NOT NULL DEFAULT 'SKIP';
ALTER TABLE "TaskImport" ADD COLUMN "replacedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "TaskImport" ADD COLUMN "changes" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "TaskImport" ADD COLUMN "rolledBackAt" DATETIME;
